---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - skiperator.kartverket.no
  resources:
  - skips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - skiperator.kartverket.no
  resources:
  - skips/finalizers
  verbs:
  - update
- apiGroups:
  - skiperator.kartverket.no
  resources:
  - skips/status
  verbs:
  - get
  - patch
  - update
