# permissions for end users to edit skips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skip-editor-role
rules:
- apiGroups:
  - skiperator.kartverket.no
  resources:
  - skips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - skiperator.kartverket.no
  resources:
  - skips/status
  verbs:
  - get
