# permissions for end users to view skips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skip-viewer-role
rules:
- apiGroups:
  - skiperator.kartverket.no
  resources:
  - skips
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - skiperator.kartverket.no
  resources:
  - skips/status
  verbs:
  - get
