apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: skiperator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Application is the Schema for the application API
      displayName: Application
      kind: Application
      name: applications.skiperator.kartverket.no
      version: v1alpha1
  description: Runs applications on SKIP in a user friendly way
  displayName: Skiperator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - skip
  links:
  - name: Skiperator
    url: https://github.com/kartverket/skiperator-poc
  maintainers:
  - email: espen.henriksen@kartverket.no
    name: Espen Henriksen
  maturity: alpha
  provider:
    name: Statens Kartverk
    url: https://github.com/kartverket/skiperator-poc
  version: 0.0.0
