---
apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: dsa-frontend-skiperatortest
spec:
  image: "ghcr.io/kartverket/dsa-frontend:anthos"
  port: 8080
  ingresses:
  - dsa-skiperatortest.test.skip.statkart.no
  replicas:
    min: 3
    max: 5
    cpuThresholdPercentage: 80
  env:
  - name: API_URL
    value: dsa-backend.skiperatortest.test.skip.statkart.no:80
  liveness:
    path: /
    port: 8080
  readiness:
    path: /
    port: 8080
  resources:
    limits:
      cpu: "1000m"
      memory: "1G"
    requests:
      cpu: "500m"
      memory: "500M"
