apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: application-sample
spec:
  image: "wardsco/sleep:latest"
  port: 8080
  ingresses:
  - testapp.dev.skip.statkart.no
  replicas:
    min: 3
    max: 5
    cpuThresholdPercentage: 80
  accessPolicy:
    inbound:
      rules:
      - application: other-app
      - application: third-app
        namespace: other-namespace
    outbound:
      rules:
      - application: other-app
      external:
      - host: nrk.no
      - host: smtp.mailgrid.com
        ports: 
        - name: smtp
          protocol: TCP
          port: 587