apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: sample-app
spec:
  image: nginx
  port: 80
  resources:
    limits:
      cpu: 500m
      memory: 10000
    requests:
      cpu: 100m
      memory: 2000
