apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: sample-app
spec:
  image: nginx
  port: 80
  resources:
    limits:
      memory: 500M
    requests:
      cpu: 5m
      memory: 250M
