apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: skiperator-system
spec:
  image: nginx
  port: 80
  resources:
    limits:
      cpu: 1000m
    requests:
      cpu: 50m
