apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  namespace: sample-app
  name: sample-app
spec:
  image: nginx
  port: 80
  labels:
    cascadeLabel: some-label
  resourceLabels:
    Deployment:
      deploymentLabel: another-label
    Service:
      serviceLabel: yet-more-label
