name: Test

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - doc/**
      - samples/**
      - README.md
      - CONTRIBUTING.md
  push:
    branches: [main]
    paths-ignore:
      - doc/**
      - samples/**
      - README.md
      - CONTRIBUTING.md

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325
      - name: Build test-image
        run: docker build -t "${IMAGE_NAME}-test" --target test .
      - name: Run tests in container
        run: docker run -it --rm --name test "${IMAGE_NAME}-test"
